# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed
#--------------------------

title: 0xanon

tagline: Cybersec student | CTF Player | Python dev

description: >-
  I'll post blogs about some automations , ctf writeups and web application security topics 
url: 'https://www.0xanon.ga'

author: Surendar

avatar: "https://avatars.githubusercontent.com/u/71928263?s=400&u=3c06331e5c5cd81f2939ecf76102d4b584812dc3&v=4"

github:
  username: anonexploiter

twitter:
  username: anonexploiter

social:
  name: anonexploiter
  email: blackdevilsurea@gmail.com
  links:
    - https://twitter.com/anonexploiter
    - https://github.com/anonexploiter

google_site_verification: wjab7JjezNdGg3dhJv8-6KbCIlqjjYnFBlntUWCuq3g

#--------------------------

baseurl: ''

timezone: Asia/Kolkata

google_analytics:
  id: 'G-1WZELSLYX1'
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false

disqus:
  comments: false
  shortname: ''


theme_mode: dark

toc: true

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: index.html
    values:
      breadcrumb:
        -
          label: Posts
  -
    scope:
      path: tags
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      dynamic_title: true
      breadcrumb:
        -
          label: Home
          url: /

sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

theme: jekyll-theme-slate
